### ISSUE TITLE
[FR]: Adding documentation about naming convention for version catalog

### ISSUE THREAD

**Issue by giangpham96** [android/nowinandroid#724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the problem

Can you tell if there is official naming conventions for version catalog used in gradle-based Kotlin project? I couldn't find any :sweat_smile:
Our problem is that we don't have a nice way to declare dependencies with 2 or more words in its name in toml file. There are a few alternatives but all of them have some cons. Consider the library: `com.braintreepayments.api:data-collector:1.2.3` .

**Approach 1**: kebab case all the way
_toml file_              `braintree-data-collector = { ... }`
_build gradle file_ `implementation(libs.braintree.data.collector)`

This creates an unnecessary layer data and implies there has to be smt else under data group

**Approach 2**: lowercase for the dependency name
_toml file_              `braintree-datacollector = { ... }`
_build gradle file_ `implementation(libs.braintree.datacollector)`

This is hard to read, esp, if the name is long and has multiple words

**Approach 3**: mixing kebab case and camel case
_toml file_              `braintree-dataCollector = { ... }`
_build gradle file_ `implementation(libs.braintree.dataCollector)`

This is simply not nice and this project is using this approach :slightly_smiling_face:

It would be awesome if developers have some guidelines for this. 
If this issue is in the wrong place, please tell me the correct one to put this request. 🙏 

### Describe the solution

I don't have any

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SimonMarquis** [comment]
> This is simply not nice

Why? This is the only approach were you did not give a "real", reason.

---

Also, I think you forgot one use case, where the base name is also a dependency, like in this example:

```toml
androidx-activity = { module = "androidx.activity:activity", version.ref = "androidx-activity" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "androidx-activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
```

I feel like, grouping by semantics always looks simpler and easier to discover (even with the "extra" layer, since autocompletion works great).
