### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by rozkminiacz** [android/nowinandroid#997]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### What happened?

A bug happened!

If you open "Interests" section using search flow, you cannot navigate to "For you" section using bottom nav.

May be similar to:
https://github.com/android/nowinandroid/issues/867

Maestro flow:

https://github.com/android/nowinandroid/assets/15570930/3a850019-a695-4bf7-927f-3af9ac306fe6

`flow.yml`
```
appId: com.google.samples.apps.nowinandroid
---
- clearState
- launchApp:
    permissions: { all: deny }
- tapOn:
    id: "com.android.permissioncontroller:id/permission_allow_button"
- runFlow: "search_flow.yml"

- tapOn: "For you"
- assertVisible: "What are you interested in?"
```

`search_flow.yml`
```
appId: com.google.samples.apps.nowinandroid
---
- tapOn: "Search"
- inputText: "publish"
- assertVisible: "Publishing & Distribution"
- tapOn: "Publishing & Distribution"
- assertVisible: "Everything to do with publishing and distributing your app, including Google Play."

- scrollUntilVisible:
    element: "Evolution of Crash Management.*"
    direction: DOWN
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
